language: go
go:
  - 1.5.3
  - 1.6
before_install:
- sudo mkdir --mode 0777 -p /var/ftp/incoming
- sudo apt-get update -qq
- sudo apt-get install -qq vsftpd
- sudo sysctl net.ipv6.conf.lo.disable_ipv6=0
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/modocache/gover
script:
- ./.run-tests
- $HOME/gopath/bin/gover
- $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
