language: go
sudo: required
dist: xenial
go:
  - 1.11.x
  - 1.12.x
before_install:
- sudo sysctl net.ipv6.conf.lo.disable_ipv6=0
- go get github.com/mattn/goveralls
- go get github.com/golang/lint/golint
script:
- goveralls -v
- golint -set_exit_status $(go list ./...)
