name: Units tests
on: [push, pull_request]
jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Setup go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
      with:
        go-version: 1.26
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run tests
      run: go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@e4612787670fc5b5f49026b8c29c5569921de1db
    - name: Coveralls
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
